### ISSUE TITLE
New device - link to configuration does not work

### ISSUE THREAD

**Issue by martin-at-schorsch** [Z-Wave-Me/home-automation#315] opened 2016-01-15 15:16 UTC
When a new device is added in expert UI of V2.2.0, the link to the configuration does not work. The page is empty.
A reload of the page showes the configuration.

**Comment by PoltoS** [comment] 2016-01-15 16:12
Duplicate of https://github.com/Z-Wave-Me/ExpertUI/issues/160

**Closed by PoltoS** 2016-01-15 16:12 UTC
